# SPDX-License-Identifier: MIT-0
---
# tasks file for postgresql_backup_restore

- name: Include depencency installs
  ansible.builtin.include_tasks: dependencies.yml
  tags: dependencies
  args:
    apply:
      tags:
        - dependencies

- name: Include backup tasks
  ansible.builtin.include_tasks: backup.yml
  tags: backup
  args:
    apply:
      tags:
        - backup

- name: Include restore tasks
  ansible.builtin.include_tasks: restore.yml
  tags: restore
  args:
    apply:
      tags:
        - restore

- name: Prune dumps
  ansible.builtin.include_tasks: prune.yml
  tags: never, prune
  args:
    apply:
      tags:
        - never
        - prune
...
